repos:
  # -- https://github.com/koalaman/shellcheck#pre-commit
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
        args: [--severity=warning] # Optionally only show errors and warnings
  # -- https://github.com/hadolint/hadolint/blob/master/docs/INTEGRATION.md#pre-commit
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint-docker
