name: pre-commit

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.16.6"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all
